### ISSUE TITLE
java.lang.IllegalArgumentException: 'other' is different type of Path

### ISSUE THREAD

**Issue by mmoayyed** [graalvm/native-build-tools#52] opened 2021-06-15 19:42 UTC
Using:

- Gradle 7.1
- Java(TM) SE Runtime Environment GraalVM EE 21.1.0 (build 11.0.11+9-LTS-jvmci-21.1-b05)
- MacOS 11.4

Plugin versions:

```groovy
  id 'org.springframework.experimental.aot' version '0.10.0' 
  id 'org.graalvm.buildtools.native' version '0.9.0' 
```

Plugin configuration:

```groovy
nativeBuild {
  imageName = "cas"
  mainClass = "org.apereo.cas.web.CasWebApplication" // Main class
  buildArgs("--no-server") // Arguments to be passed to native-image invocation
  debug = false // Determines if debug info should be generated
  verbose = false
  fallback = false
  // classpath("dir1", "dir2") // Adds "dir1" and "dir2" to the classpath
  //jvmArgs("flag") // Passes 'flag' directly to the JVM running the native image builder
  //runtimeArgs("--help") // Passes '--help' to built image, during "nativeRun" task
  //systemProperties = [name1: 'value1', name2: 'value2'] // Sets system properties
  agent = false // Can be also set on command line using '-Pagent'
  persistConfig = false // Used in conjunction with 'agent' to save its output to META-INF
}

```

Running:

```bash
./gradlew nativeBuild -x test -x check     
```

The following trace shows up:

```bash
> Task :nativeBuild
[cas:78976]    classlist:  14,612.65 ms,  2.30 GB
[cas:78976]        setup:   1,159.75 ms,  2.30 GB
Fatal error:java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: 'other' is different type of Path
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
        at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:499)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:370)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:531)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:568)
Caused by: java.lang.IllegalArgumentException: 'other' is different type of Path
        at java.base/sun.nio.fs.UnixPath.relativize(UnixPath.java:429)
        at java.base/sun.nio.fs.UnixPath.relativize(UnixPath.java:43)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
        at com.oracle.svm.enterprise.core.b.<init>(stripped:74)
        at com.oracle.svm.enterprise.hosted.a.afterRegistration(stripped:25)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$17(NativeImageGenerator.java:874)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:874)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:580)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:495)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

I can provide a sample project, if you find that useful.

**Comment by gradinac** [comment] 2021-06-18 14:58
Hey @mmoayyed, thank you for the bug report!
Looking at the stack trace, this seems to be a bug in a GraalVM EE feature unrelated to the build tools:
```
 at com.oracle.svm.enterprise.hosted.a.afterRegistration(stripped:25)
```
Could you try building your application manually, without the plugin and see if this still happens?
If you could provide a sample reproducer, that would help a lot! :)

**Comment by mmoayyed** [comment] 2021-06-18 15:03
Here is a reproducer:
[Archive.zip](https://github.com/graalvm/native-build-tools/files/6677850/Archive.zip)

Unzip and build with `./gradlew nativeBuild -x test -x check`

And yes, the application builds just fine without the plugin.

Thank you.

**Comment by gradinac** [comment] 2021-06-18 16:25
Thank you for the reproducer! I've managed to reproduce this on 21.1 - the culprit seems to have been a bug in an EE feature that has subsequently been fixed. The core reason for the bug is that the `gradle` plugin overrides the `-H:Path` argument with a non-absolute one, resulting in the above error.
The bug has already been fixed on GraalVM EE `master`, however, running the build (both with EE and CE) yields a different error:
```bash
Error: Classes that should be initialized at run time got initialized during image building:
 org.springframework.util.unit.DataSize was unintentionally initialized at build time. To see why org.springframework.util.unit.DataSize got initialized use --trace-class-initialization=org.springframework.util.unit.DataSize
```
However, this seems unrelated to the original issue

While investigating this, I've noticed that we may sometimes override user specified `-H:Name` and `-H:Path` arguments - we should probably avoid doing that.

**Comment by mmoayyed** [comment] 2021-06-18 17:26
Thanks much for the analysis. I suppose I have to wait until GraalVM EE issues a patch or a release comes out, which is no problem at all. 

The error you note above is likely something to take up with the spring-native projects. I can look into it more once the GraalVM release comes out.

**Comment by gradinac** [comment] 2021-06-18 17:39
Sounds good! I think we will have a release soon, but in case you want to try it out beforehand on a CE build, we have CE dev builds available here: https://github.com/graalvm/graalvm-ce-dev-builds/releases
Unfortunately, due to the way the gradle plugin currently adds the `-H:Path` argument, I don't think there's an easy workaround to get past that step in the current plugin version

**Comment by gradinac** [comment] 2021-06-22 10:17
As we've confirmed the original source of this issue, I'll close this ticket. I've opened #64 to track the problem we've uncovered here - user arguments should always have precedence over our internally specified arguments.

**Closed by gradinac** 2021-06-22 10:17 UTC
