### ISSUE TITLE
JDK selection.

### ISSUE THREAD

**Issue by tarric1** [graalvm/native-build-tools#172] opened 2021-11-29 13:41 UTC
On my build machine, I've different JDKs installed and I use maven properties, configured in settings.xml, to choose the right JDK to use or alternativelly I use toolchains as second option.

The native-maven-plugin doesn't allow the selection of the JDK to use and it uses always the JAVA_HOME environment variable,

I think that this is a huge problem that limits the flexibility of building systems.

**Comment by lazar-mitrovic** [comment] 2021-11-29 13:55
Might be a duplicate of #143.

I believe you should be able to select your GraalVM location using `GRAALVM_HOME` env variable until #149 is merged.

**Comment by tarric1** [comment] 2021-11-29 14:08
I'm using version 0.9.7.1 and it isn't considered neither GRAALVM_HOME nor toolchains.
What is the version to use?

**Comment by lazar-mitrovic** [comment] 2021-11-29 14:24
`0.9.7.1` is the latest so it should be fine.

Logic for detecting `native-image` executable is located here: https://github.com/graalvm/native-build-tools/blob/master/native-maven-plugin/src/main/java/org/graalvm/buildtools/Utils.java#L105-L123

It should check for `native-image` executable presence in following order:
- `JAVA_HOME`, 
- `PATH` variable,
- `GRAALVM_HOME`

**Comment by tarric1** [comment] 2021-11-29 15:18
I don't know why, but it doesn't work:

![image](https://user-images.githubusercontent.com/23168111/143893463-667f0f2d-1f0d-4823-88a2-384fe8d3f022.png)

![image](https://user-images.githubusercontent.com/23168111/143894001-a266d4cb-cf78-4ae4-ae04-ef42ea606801.png)

**Closed** 2021-11-29 16:19 UTC

**Comment by lazar-mitrovic** [comment] 2021-11-29 16:21
Please check if your issue is resolved in latest snapshot (see `Testing pre-releases` section [here](https://graalvm.github.io/native-build-tools/latest/maven-plugin.html#_registering_the_plugin) for steps required in order to enable snapshots)

**Comment by lazar-mitrovic** [comment] 2021-11-29 18:37
Oh sorry, it seems like the snapshot publishing is broken ATM, ignore my last comment.
