### ISSUE TITLE
Add an artifact that downloads GraalVM and Native Image

### ISSUE THREAD

**Issue by lazar-mitrovic** [graalvm/native-build-tools#100] opened 2021-07-09 11:12 UTC
It can be a bit tricky for the end users to download and configure GraalVM. We can automate this process by providing an artifact that downloads and configures GraalVM and Native Image. 

This artifact would be invoked by both Gradle and Maven plugins and would be configurable trough them (by specifying version, distribution, and/or even the URL) using extensions and configuration options.

Note that Windows support for this might be a bit harder (but certainly doable).

**Comment by graemerocher** [comment] 2021-07-09 12:29
Gradle already supports the notion of tool chains which this should support imo

**Comment by melix** [comment] 2021-07-12 07:15
I totally agree that we should provide a more build-tool friendly API to fetch a GraalVM build _with native image preinstalled_. Gradle's toolchain mechanism is two fold:

1. it can identify JDK installations in "well-known" places: from `$PATH`, from OS specific paths (`/usr/lib/..`) or from common tools which are able to install JDKs by themselves (e.g SDKMan!).
2. if _no suitable JDK is found_, it tries to download a compatible version from AdoptOpenJDKhttps://docs.gradle.org/current/userguide/toolchains.html#sec:provisioning

For both, there is a problem with GraalVM:

In 1., the problem is that _even if you identify a GraalVM toolchain_, there's no guarantee that the `native-image` tool would be installed. There should be a way to get a GraalVM SDK _with the native image tool preinstalled_.

For 2., the automatic provisioning is optional in Gradle. It uses the AdoptOpenJDK API to do this, but [Gradle can be configured to use a different base URL](https://docs.gradle.org/current/userguide/toolchains.html#sec:provisioning) for the download service. It means that GraalVM _could_ provide an AdoptOpenJDK compatible API service to supply JDKs. It should be relatively easy to do so. Note that the API itself has nothing specific to Adopt. It can be used by any other vendor. However, again, what would be downloaded would have to come with `native-image` preinstalled to be build tool friendly.

**Comment by melix** [comment] 2021-08-13 13:03
Related: https://github.com/gradle/gradle/pull/18028

**Comment by lazar-mitrovic** [comment] 2022-06-30 15:49
Related Gradle Roadmap entry: https://github.com/gradle/build-tool-roadmap/issues/29

**Comment by sschuberth** [comment] 2022-07-27 10:35
> It can be a bit tricky for the end users to download and configure GraalVM. We can automate this process by providing an artifact that downloads and configures GraalVM and Native Image.

Agreed. For Gradle, that's basically the only reason why we're using https://github.com/palantir/gradle-graal in https://github.com/oss-review-toolkit/ort rather than the Gradle plugin from this repo. I'm really hoping for https://github.com/gradle/gradle/pull/18028 to land soon (it's scheduled for Gradle 7.6 currently) to address the matter generically in Gradle itself.

**Comment by frank-dspeed** [comment] 2022-08-02 05:44
what is the problem here i simply use
1. download graalvm-ce and extract
2. install native-image installs it or returns true if installed
```
$GRAALVM/bin/gu install native-image
```

so ensure installed is not a problem ??

**Comment by cvmocanu** [comment] 2022-08-12 14:46
> what is the problem here i simply use
> 
> 1. download graalvm-ce and extract
> 2. install native-image installs it or returns true if installed
> 
> ```
> $GRAALVM/bin/gu install native-image
> ```
> 
> so ensure installed is not a problem ??

@frank-dspeed, let me re-phrase your question: _"What is the point of Gradle toolchain auto provisioning?"_.
And the answer is: convenience - you checkout a git project and it just works. No need to point people to a readme file with step-by-step instructions. It just works.
That is also why we use the Gradle wrapper instead of asking everyone to install Gradle.

**Comment by frank-dspeed** [comment] 2022-08-14 07:59
@cvmocanu do i understand you correct your using nativ image gradle and graal with stock JDK?

**Comment by cvmocanu** [comment] 2022-08-14 11:30
@frank-dspeed: I'm using the https://github.com/palantir/gradle-graal  Gradle plugin. The plugin adds a `nativeImage` task which compiles to native binaries.
I assume the Java source->bytecode compilation is done with a stock JDK, but I'm not sure if the plugin changes the Java compiler configuration or not.

As others said, that plugin does auto-provisioning (it downloads the specified version of GraalVM community to `~/.gradle/caches/com.palantir.graal/<version>`, if it's not already downloaded locally). This is really convenient.

**Comment by cvmocanu** [comment] 2022-08-14 11:30
I would love to use the official plugin (this one) though, instead of the palantir one.

**Comment by sschuberth** [comment] 2022-11-01 11:26
Just wondering, could the work on this topic for the Gradle plugin already start now that Gradle 7.6 RC1 [added support for Java Toolchain downloads from arbitrary repositories](https://docs.gradle.org/7.6-rc-1/release-notes.html#added-support-for-java-toolchain-downloads-from-arbitrary-repositories), despite https://github.com/gradle/gradle/pull/18028 not being merged yet?

**Comment by frank-dspeed** [comment] 2022-11-01 12:24
i guess this gets solved as most of the graalvm parts get moved now to stock openjdk

**Comment by sschuberth** [comment] 2022-11-23 08:38
> i guess this gets solved as most of the graalvm parts get moved now to stock openjdk

I'm not sure whether it's worth waiting for that to happen in a new JDK release. Releasing a new plugin version that's able to bootstrap GraalVM with native image support now seems to be the much lower hanging fruit.

**Comment by sschuberth** [comment] 2022-11-23 09:35
> simply create a bash script and call it a day much faster written then java or use kotlin and not bash.

That, however, is not what *I* wanted to say 😉 : Adding a few lines of Kotlin / Java code to implement a [toolchain resolver plugin](https://docs.gradle.org/7.6-rc-4/userguide/toolchain_plugins.html) is quicker than waiting for a new JDK release, and much more generic / self-contained than requiring developers to run an external script.

**Comment by frank-dspeed** [comment] 2022-11-23 09:53
@sschuberth i make it even more generic i am working on a https://google.github.io/blockly-samples/plugins/block-dynamic-connection/test/ graalvm build tool ok it is not related to graalvm but it can build graalvm and that is in my view the most generic as it runs generic in my browser and is able to execute it directly else where or save it to a local file.

**Comment by fniephaus** [comment] 2023-10-16 13:14
GraalVM has become more easily accessible in the last couple of months (e.g., SDKMAN!, GitHub Actions, script-friendly download URLs). It is also integrated in the Foojay API, which can be used by Gradle's toolchain detection.

Given this issue hasn't been updated for more than a year, I'm going to close it for now. In case you still see a problem or potentials for improvement, please speak up :)

**Closed by fniephaus** 2023-10-16 13:14 UTC
Labels: enhancement, discussion

**Comment by rd-zahari-aleksiev** [comment] 2025-03-15 22:02
and also Foojay is downloading GraalVM w/out the native image tool ...

**Comment by frank-dspeed** [comment] 2025-03-28 08:32
@cvmocanu you should handle that maybe via git hooks you can easy add a script that checks for the current graalvm version and the expected one and then does the right thing. It is almost always most clever to handle Project wide expectations in the Project Repo.

**Comment by cvmocanu** [comment] 2025-03-28 08:45
@frank-dspeed : thanks for the suggestion, but it doesn't work using modern development practices. In a CI-CD environment, you don't (or should not) have access to the build server nodes for things like these. You want your build process (either GitHub actions, or Gradle, something else) to auto-provision toolkits for you.

Having the auto-provisioning as part of Gradle simplifies things, since you don't have to do different things on the local development machine and on the build/integration server nodes.

Moreover, if I had to do it myself, I would very much prefer writing a custom Gradle plugin, using a proper programming language like Kotlin or Java, rather than writing a shell script using something like bash, which is so bad that even calling it a language would offend other languages :) (and I do know how to properly write bash)
