### ISSUE TITLE
[GR-43413] java.nio.file.InvalidPathException: Illegal char < > at index 3

### ISSUE THREAD

**Issue by Bejenar** [graalvm/native-build-tools#318] opened 2022-09-27 19:29 UTC
Command executed `mvn package -Dpackaging=native-image
`

 - OS: `Windows`
 - GraalVM Version  `ce-22.2.0`
 - Java Version `17`

logs:
(Although log says the path is `D:\ Java\ Micronaut Sandbox\ aws-lambda\ aws-lambda\ target\ aws-lambda-0.1.jar`, it is actually 
`D:\Java\Micronaut Sandbox\aws-lambda\aws-lambda\target\aws-lambda-0.1.jar` so symbols are coming out of nowhere
```
[INFO] 
[INFO] -----------------------< com.example:aws-lambda >-----------------------
[INFO] Building aws-lambda 0.1
[INFO] ----------------------------[ native-image ]----------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ aws-lambda ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ aws-lambda ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- micronaut-maven-plugin:3.4.0:aot-analysis (default-aot-analysis) @ aws-lambda ---
[INFO] 
[INFO] --- micronaut-maven-plugin:3.4.0:graalvm-resources (default-graalvm-resources) @ aws-lambda ---
[INFO] Generating D:\Java\Micronaut Sandbox\aws-lambda\aws-lambda\target\classes\META-INF\native-image\com.example\aws-lambda\resource-config.json
[INFO] 
[INFO] --- maven-jar-plugin:3.2.2:jar (default-jar) @ aws-lambda ---
[INFO] Building jar: D:\Java\Micronaut Sandbox\aws-lambda\aws-lambda\target\aws-lambda-0.1.jar
[INFO] 
[INFO] --- native-maven-plugin:0.9.13:build (default-build) @ aws-lambda ---
[INFO] Found GraalVM installation from JAVA_HOME variable.
[INFO] ImageClasspath Entry: com.example:aws-lambda:native-image:0.1 (file:///D:/Java/Micronaut%20Sandbox/aws-lambda/aws-lambda/target/aws-lambda-0.1.jar)
[INFO] ImageClasspath Entry: org.slf4j:jcl-over-slf4j:jar:1.7.36:compile (file:///C:/Users/jion9/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.36/jcl-over-slf4j-1.7.36.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-core:jar:3.7.0:compile (file:///C:/Users/jion9/.m2/repository/io/micronaut/micronaut-core/3.7.0/micronaut-core-3.7.0.jar)
[INFO] ImageClasspath Entry: io.micronaut.aws:micronaut-function-aws:jar:3.9.2:compile (file:///C:/Users/jion9/.m2/repository/io/micronaut/aws/micronaut-function-aws/3.9.2/micronaut-function-aws-3.9.2.jar)
[INFO] ImageClasspath Entry: io.netty:netty-resolver:jar:4.1.82.Final:runtime (file:///C:/Users/jion9/.m2/repository/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-http-server:jar:3.7.0:compile (file:///C:/Users/jion9/.m2/repository/io/micronaut/micronaut-http-server/3.7.0/micronaut-http-server-3.7.0.jar)
[INFO] ImageClasspath Entry: javax.ws.rs:javax.ws.rs-api:jar:2.1:compile (file:///C:/Users/jion9/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.jar)
[INFO] ImageClasspath Entry: org.slf4j:slf4j-api:jar:1.7.36:compile (file:///C:/Users/jion9/.m2/repository/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar)
[INFO] ImageClasspath Entry: io.micronaut.aws:micronaut-function-aws-api-proxy:jar:3.9.2:compile (file:///C:/Users/jion9/.m2/repository/io/micronaut/aws/micronaut-function-aws-api-proxy/3.9.2/micronaut-function-aws-api-proxy-3.9.2.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-context:jar:3.7.0:compile (file:///C:/Users/jion9/.m2/repository/io/micronaut/micronaut-context/3.7.0/micronaut-context-3.7.0.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-websocket:jar:3.7.0:compile (file:///C:/Users/jion9/.m2/repository/io/micronaut/micronaut-websocket/3.7.0/micronaut-websocket-3.7.0.jar)
[INFO] ImageClasspath Entry: javax.validation:validation-api:jar:2.0.1.Final:compile (file:///C:/Users/jion9/.m2/repository/javax/validation/validation-api/2.0.1.Final/validation-api-2.0.1.Final.jar)
[INFO] ImageClasspath Entry: com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.4:compile (file:///C:/Users/jion9/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.13.4/jackson-datatype-jsr310-2.13.4.jar)
[INFO] ImageClasspath Entry: io.netty:netty-handler:jar:4.1.82.Final:runtime (file:///C:/Users/jion9/.m2/repository/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar)
[WARNING] jar:file:///C:/Users/jion9/.m2/repository/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar!/META-INF/native-image/io.netty/handler/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[INFO] ImageClasspath Entry: javax.annotation:javax.annotation-api:jar:1.3.2:compile (file:///C:/Users/jion9/.m2/repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-validation:jar:3.7.0:compile (file:///C:/Users/jion9/.m2/repository/io/micronaut/micronaut-validation/3.7.0/micronaut-validation-3.7.0.jar)
[WARNING] jar:file:///C:/Users/jion9/.m2/repository/io/micronaut/micronaut-validation/3.7.0/micronaut-validation-3.7.0.jar!/META-INF/native-image/io.micronaut.validation/micronaut-validation/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[INFO] ImageClasspath Entry: io.micronaut:micronaut-router:jar:3.7.0:compile (file:///C:/Users/jion9/.m2/repository/io/micronaut/micronaut-router/3.7.0/micronaut-router-3.7.0.jar)
[INFO] ImageClasspath Entry: io.micronaut.aws:micronaut-aws-common:jar:3.9.2:compile (file:///C:/Users/jion9/.m2/repository/io/micronaut/aws/micronaut-aws-common/3.9.2/micronaut-aws-common-3.9.2.jar)
[INFO] ImageClasspath Entry: ch.qos.logback:logback-core:jar:1.2.11:runtime (file:///C:/Users/jion9/.m2/repository/ch/qos/logback/logback-core/1.2.11/logback-core-1.2.11.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-runtime:jar:3.7.0:compile (file:///C:/Users/jion9/.m2/repository/io/micronaut/micronaut-runtime/3.7.0/micronaut-runtime-3.7.0.jar)
[INFO] ImageClasspath Entry: io.netty:netty-codec-http:jar:4.1.82.Final:runtime (file:///C:/Users/jion9/.m2/repository/io/netty/netty-codec-http/4.1.82.Final/netty-codec-http-4.1.82.Final.jar)
[WARNING] jar:file:///C:/Users/jion9/.m2/repository/io/netty/netty-codec-http/4.1.82.Final/netty-codec-http-4.1.82.Final.jar!/META-INF/native-image/io.netty/codec-http/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[INFO] ImageClasspath Entry: io.micronaut:micronaut-function:jar:3.7.0:compile (file:///C:/Users/jion9/.m2/repository/io/micronaut/micronaut-function/3.7.0/micronaut-function-3.7.0.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-http:jar:3.7.0:compile (file:///C:/Users/jion9/.m2/repository/io/micronaut/micronaut-http/3.7.0/micronaut-http-3.7.0.jar)
[WARNING] jar:file:///C:/Users/jion9/.m2/repository/io/micronaut/micronaut-http/3.7.0/micronaut-http-3.7.0.jar!/META-INF/native-image/io.micronaut.http/micronaut-http/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[INFO] ImageClasspath Entry: io.micronaut:micronaut-http-netty:jar:3.7.0:runtime (file:///C:/Users/jion9/.m2/repository/io/micronaut/micronaut-http-netty/3.7.0/micronaut-http-netty-3.7.0.jar)
[INFO] ImageClasspath Entry: com.amazonaws.serverless:aws-serverless-java-container-core:jar:1.8.2:compile (file:///C:/Users/jion9/.m2/repository/com/amazonaws/serverless/aws-serverless-java-container-core/1.8.2/aws-serverless-java-container-core-1.8.2.jar)
[INFO] ImageClasspath Entry: ch.qos.logback:logback-classic:jar:1.2.11:runtime (file:///C:/Users/jion9/.m2/repository/ch/qos/logback/logback-classic/1.2.11/logback-classic-1.2.11.jar)
[INFO] ImageClasspath Entry: commons-codec:commons-codec:jar:1.11:compile (file:///C:/Users/jion9/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar)
[INFO] ImageClasspath Entry: org.apache.httpcomponents:httpcore:jar:4.4.13:compile (file:///C:/Users/jion9/.m2/repository/org/apache/httpcomponents/httpcore/4.4.13/httpcore-4.4.13.jar)
[INFO] ImageClasspath Entry: io.netty:netty-codec:jar:4.1.82.Final:runtime (file:///C:/Users/jion9/.m2/repository/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar)
[INFO] ImageClasspath Entry: org.apache.httpcomponents:httpmime:jar:4.5.13:compile (file:///C:/Users/jion9/.m2/repository/org/apache/httpcomponents/httpmime/4.5.13/httpmime-4.5.13.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-inject:jar:3.7.0:compile (file:///C:/Users/jion9/.m2/repository/io/micronaut/micronaut-inject/3.7.0/micronaut-inject-3.7.0.jar)
[INFO] ImageClasspath Entry: com.sun.activation:jakarta.activation:jar:1.2.2:compile (file:///C:/Users/jion9/.m2/repository/com/sun/activation/jakarta.activation/1.2.2/jakarta.activation-1.2.2.jar)
[INFO] ImageClasspath Entry: com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.13.4:compile (file:///C:/Users/jion9/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.13.4/jackson-datatype-jdk8-2.13.4.jar)
[INFO] ImageClasspath Entry: org.apache.httpcomponents:httpclient:jar:4.5.13:compile (file:///C:/Users/jion9/.m2/repository/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar)
[INFO] ImageClasspath Entry: jakarta.annotation:jakarta.annotation-api:jar:2.1.1:compile (file:///C:/Users/jion9/.m2/repository/jakarta/annotation/jakarta.annotation-api/2.1.1/jakarta.annotation-api-2.1.1.jar)
[INFO] ImageClasspath Entry: io.netty:netty-codec-http2:jar:4.1.82.Final:runtime (file:///C:/Users/jion9/.m2/repository/io/netty/netty-codec-http2/4.1.82.Final/netty-codec-http2-4.1.82.Final.jar)
[WARNING] jar:file:///C:/Users/jion9/.m2/repository/io/netty/netty-codec-http2/4.1.82.Final/netty-codec-http2-4.1.82.Final.jar!/META-INF/native-image/io.netty/codec-http2/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[INFO] ImageClasspath Entry: com.fasterxml.jackson.core:jackson-annotations:jar:2.13.4:compile (file:///C:/Users/jion9/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.13.4/jackson-annotations-2.13.4.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-buffer-netty:jar:3.7.0:runtime (file:///C:/Users/jion9/.m2/repository/io/micronaut/micronaut-buffer-netty/3.7.0/micronaut-buffer-netty-3.7.0.jar)
[INFO] ImageClasspath Entry: io.netty:netty-common:jar:4.1.82.Final:runtime (file:///C:/Users/jion9/.m2/repository/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar)
[WARNING] jar:file:///C:/Users/jion9/.m2/repository/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar!/META-INF/native-image/io.netty/common/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[INFO] ImageClasspath Entry: com.fasterxml.jackson.core:jackson-core:jar:2.13.4:compile (file:///C:/Users/jion9/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.13.4/jackson-core-2.13.4.jar)
[INFO] ImageClasspath Entry: jakarta.inject:jakarta.inject-api:jar:2.0.1:compile (file:///C:/Users/jion9/.m2/repository/jakarta/inject/jakarta.inject-api/2.0.1/jakarta.inject-api-2.0.1.jar)
[INFO] ImageClasspath Entry: io.netty:netty-buffer:jar:4.1.82.Final:runtime (file:///C:/Users/jion9/.m2/repository/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar)
[WARNING] jar:file:///C:/Users/jion9/.m2/repository/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[INFO] ImageClasspath Entry: commons-fileupload:commons-fileupload:jar:1.4:compile (file:///C:/Users/jion9/.m2/repository/commons-fileupload/commons-fileupload/1.4/commons-fileupload-1.4.jar)
[INFO] ImageClasspath Entry: com.amazonaws:aws-lambda-java-core:jar:1.2.1:compile (file:///C:/Users/jion9/.m2/repository/com/amazonaws/aws-lambda-java-core/1.2.1/aws-lambda-java-core-1.2.1.jar)
[INFO] ImageClasspath Entry: org.yaml:snakeyaml:jar:1.32:compile (file:///C:/Users/jion9/.m2/repository/org/yaml/snakeyaml/1.32/snakeyaml-1.32.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-jackson-core:jar:3.7.0:compile (file:///C:/Users/jion9/.m2/repository/io/micronaut/micronaut-jackson-core/3.7.0/micronaut-jackson-core-3.7.0.jar)
[INFO] ImageClasspath Entry: io.netty:netty-transport-native-unix-common:jar:4.1.82.Final:runtime (file:///C:/Users/jion9/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar)
[INFO] ImageClasspath Entry: com.fasterxml.jackson.core:jackson-databind:jar:2.13.4:compile (file:///C:/Users/jion9/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.13.4/jackson-databind-2.13.4.jar)
[INFO] ImageClasspath Entry: io.projectreactor:reactor-core:jar:3.4.23:runtime (file:///C:/Users/jion9/.m2/repository/io/projectreactor/reactor-core/3.4.23/reactor-core-3.4.23.jar)
[INFO] ImageClasspath Entry: commons-io:commons-io:jar:2.2:compile (file:///C:/Users/jion9/.m2/repository/commons-io/commons-io/2.2/commons-io-2.2.jar)
[INFO] ImageClasspath Entry: io.netty:netty-transport:jar:4.1.82.Final:runtime (file:///C:/Users/jion9/.m2/repository/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar)
[WARNING] jar:file:///C:/Users/jion9/.m2/repository/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar!/META-INF/native-image/io.netty/transport/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[INFO] ImageClasspath Entry: io.micronaut:micronaut-jackson-databind:jar:3.7.0:compile (file:///C:/Users/jion9/.m2/repository/io/micronaut/micronaut-jackson-databind/3.7.0/micronaut-jackson-databind-3.7.0.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-aop:jar:3.7.0:compile (file:///C:/Users/jion9/.m2/repository/io/micronaut/micronaut-aop/3.7.0/micronaut-aop-3.7.0.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-json-core:jar:3.7.0:compile (file:///C:/Users/jion9/.m2/repository/io/micronaut/micronaut-json-core/3.7.0/micronaut-json-core-3.7.0.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-core-reactive:jar:3.7.0:compile (file:///C:/Users/jion9/.m2/repository/io/micronaut/micronaut-core-reactive/3.7.0/micronaut-core-reactive-3.7.0.jar)
[INFO] ImageClasspath Entry: org.reactivestreams:reactive-streams:jar:1.0.4:compile (file:///C:/Users/jion9/.m2/repository/org/reactivestreams/reactive-streams/1.0.4/reactive-streams-1.0.4.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-http-client-core:jar:3.7.0:compile (file:///C:/Users/jion9/.m2/repository/io/micronaut/micronaut-http-client-core/3.7.0/micronaut-http-client-core-3.7.0.jar)
[INFO] Executing: A:\Program Files\Java\graalvm-ce-java17-22.2.0\bin\native-image.cmd @C:\Users\jion9\AppData\Local\Temp\native-image6645542244804852343args
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char < > at index 3: D:\ Java\ Micronaut Sandbox\ aws-lambda\ aws-lambda\ target\ aws-lambda-0.1.jar
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.nio.file.Path.of(Path.java:147)
	at java.nio.file.Paths.get(Paths.java:69)
	at com.oracle.svm.core.util.ClasspathUtils.stringToClasspath(ClasspathUtils.java:52)
	at com.oracle.svm.driver.NativeImage.addCustomImageClasspath(NativeImage.java:1568)
	at com.oracle.svm.driver.DefaultOptionHandler.processClasspathArgs(DefaultOptionHandler.java:413)
	at com.oracle.svm.driver.DefaultOptionHandler.consume(DefaultOptionHandler.java:69)
	at com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:1498)
	at com.oracle.svm.driver.DefaultOptionHandler.consume(DefaultOptionHandler.java:200)
	at com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:1498)
	at com.oracle.svm.driver.NativeImage.processNativeImageArgs(NativeImage.java:1756)
	at com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:962)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1404)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1374)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1361)

```

 pom.xml
 ```xml
 <?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>aws-lambda</artifactId>
  <version>0.1</version>
  <packaging>${packaging}</packaging>

  <parent>
    <groupId>io.micronaut</groupId>
    <artifactId>micronaut-parent</artifactId>
    <version>3.7.0</version>
  </parent>

  <properties>
    <packaging>jar</packaging>
    <jdk.version>17</jdk.version>
    <release.version>17</release.version>
    <micronaut.version>3.7.0</micronaut.version>
    <micronaut.runtime>lambda</micronaut.runtime>
    <exec.mainClass>com.example.Application</exec.mainClass>
  </properties>

  <repositories>
    <repository>
      <id>central</id>
      <url>https://repo.maven.apache.org/maven2</url>
    </repository>
  </repositories>

  <dependencies>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-inject</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-validation</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.micronaut.aws</groupId>
      <artifactId>micronaut-function-aws-api-proxy</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.micronaut.aws</groupId>
      <artifactId>micronaut-function-aws-api-proxy-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-http-client</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-jackson-databind</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>jakarta.annotation</groupId>
      <artifactId>jakarta.annotation-api</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>io.micronaut.test</groupId>
      <artifactId>micronaut-test-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>io.micronaut.build</groupId>
        <artifactId>micronaut-maven-plugin</artifactId>
      </plugin>
      
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <!-- Uncomment to enable incremental compilation -->
          <!-- <useIncrementalCompilation>false</useIncrementalCompilation> -->

          <annotationProcessorPaths combine.children="append">
          </annotationProcessorPaths>
          <compilerArgs>
            <arg>-Amicronaut.processing.group=com.example</arg>
            <arg>-Amicronaut.processing.module=aws-lambda</arg>
          </compilerArgs>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>

 ```

**Comment by kristofdho** [comment] 2022-11-04 08:35
I'm seeing the same thing on my end, but with the native-build-tools directly (without micronaut layer in between). This is caused by having a space on your path (anywhere, it reports it at index 3 every time). Through the build tools there are no additional spaces in the reported path.

Adding `<useArgFile>false</useArgFile>` to the plugin config fixes it if your path isn't too long and you don't run into other issues.
I don't know if you can configure that through the micronaut plugin, but either way this is something that should be fixed in the native-build-tools.

**Comment by sdeleuze** [comment] 2022-11-15 13:46
I can reproduce with Gradle as well on Windows. Pretty strange issue, I suspect an underlying bug in `native-image` argfile handling, so we may need to open an issue in https://github.com/oracle/graal/issues.

**Comment by huangxiuqi** [comment] 2022-11-28 09:08
The same problem, if replace all \\ in the args file with /, and then run native-image.cmd @target\tmp\native-image-xxx.args, it can be compiled normally.

**Comment by CXwudi** [comment] 2022-12-02 05:09
The same problem here. I am building a Spring Boot 3 native app on Windows 10. And just like previous ppl said, to make it compile, I have to make sure there is no space in the project path

**Comment by weifengze** [comment] 2022-12-19 12:49
The same problem here.
`[INFO] --- native-maven-plugin:0.9.18:compile (default-cli) @ spring-boot3-demo ---
[INFO] Found GraalVM installation from JAVA_HOME variable.
[INFO] [graalvm reachability metadata repository for ch.qos.logback:logback-classic:1.4.5]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for ch.qos.logback:logback-classic:1.4.5]: Configuration directory is ch.qos.logback\logback-classic\1.4.1
[INFO] [graalvm reachability metadata repository for org.apache.tomcat.embed:tomcat-embed-core:10.1.1]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for org.apache.tomcat.embed:tomcat-embed-core:10.1.1]: Configuration directory is org.apache.tomcat.embed\tomcat-embed-core\10.0.20
[INFO] [graalvm reachability metadata repository for org.hdrhistogram:HdrHistogram:2.1.12]: Configuration directory is org.hdrhistogram\HdrHistogram\2.1.12
[INFO] Executing: C:\Program Files\Java\graalvm-ce-java17-22.3.0\bin\native-image.cmd @target\tmp\native-image-1389472971425881411.args
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char < > at index 3: E:\ JavaProjectSpace\ spring-boot3-demo\ target\ classes
        at java.base@17.0.5/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base@17.0.5/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base@17.0.5/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base@17.0.5/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base@17.0.5/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
        at java.base@17.0.5/java.nio.file.Path.of(Path.java:147)
        at java.base@17.0.5/java.nio.file.Paths.get(Paths.java:69)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.ClasspathUtils.stringToClasspath(ClasspathUtils.java:52)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.addCustomImageClasspath(NativeImage.java:1582)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.DefaultOptionHandler.processClasspathArgs(DefaultOptionHandler.java:417)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.DefaultOptionHandler.consume(DefaultOptionHandler.java:69)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:1512)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.DefaultOptionHandler.consume(DefaultOptionHandler.java:204)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:1512)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.processNativeImageArgs(NativeImage.java:1770)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:959)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.build(NativeImage.java:1417)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1387)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.main(NativeImage.java:1374)`

**Comment by sdeleuze** [comment] 2023-01-02 15:37
@fniephaus Could you please check if a related bug should be created on https://github.com/oracle/graal/issues?

**Comment by fniephaus** [comment] 2023-01-02 19:12
@sdeleuze I'll take a look later this week.

**Comment by fniephaus** [comment] 2023-01-06 11:56
I can reproduce the problem but I am still not sure whether this is a bug in the NBT or in Native Image. I will update this as soon as I know more...

**Comment by weifengze** [comment] 2023-01-06 12:10
https://github.com/graalvm/native-build-tools/issues/318#issuecomment-1357617487
I installed Windows 10 LTCS in VMware and reconfigured GraalVM related dependencies and this time it ran successfully.
The file path to GraalVM in the virtual machine is C:graalvmgraalvm-ce-java17-22.3.0

**Comment by fniephaus** [comment] 2023-01-06 12:19
@weifengze it happens when the path to the project contains a space, not the GraalVM installation. I have a hunch what's going on but I'm not there yet.

**Comment by fniephaus** [comment] 2023-01-09 12:57
I believe I found the root cause and have a fix in flight: https://github.com/oracle/graal/pull/5725. Please try again when the fix becomes available through a [dev build](https://github.com/graalvm/graalvm-ce-dev-builds/releases/latest). Let me know if the problem persists so that I can re-open this issue.

**Closed by fniephaus** 2023-01-09 12:57 UTC
Labels: bug
